#
# Executes commands at the start of an interactive session.
#

alias code="cd ~/code"
alias vs="/usr/local/bin/code"
alias serve="python -m SimpleHTTPServer"
alias au="find . -name "
alias py=ipython

export PYTHONDONTWRITEBYTECODE=1
export EDITOR=vim

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi